APP_OPTIM := release
APP_PLATFORM := android-9
APP_STL := gnustl_static
APP_CPPFLAGS += -frtti
APP_CPPFLAGS += -fexceptions
APP_CPPFLAGS += -DANDROID
APP_ABI := armeabi armeabi-v7a arm64-v8a x86 x86_64 mips mips64
APP_MODULES := cares ssl crypto curl
NDK_TOOLCHAIN_VERSION := clang
